[install]
is_configured = 1
state = enabled

[launcher]
author = Fahad Yousuf
description = Search-time knowledge and sourcetype classification for VyOS syslog and Linux netfilter firewall logs.
version = 0.1.0

[ui]
is_visible = 0
label = Technology Add-on for VyOS

[package]
id = TA-vyos
