[vyos_netfilter]
search = sourcetype=vyos:netfilter

[vyos_syslog]
search = sourcetype=vyos:syslog

[vyos_kea_dhcp]
search = sourcetype=vyos:kea:dhcp

[network_traffic]
search = sourcetype=vyos:netfilter
